name=Loom
version=4.9.1
author=OPEnSLab-OSU
maintainer=OPEnSLab-OSU
sentence=An Internet of Things rapid-prototyping system for environmental sensing.
paragraph=Loom provides modular sensing, logging, communication, and power-management components for environmental monitoring deployments.
category=Device Control
url=https://github.com/OPEnSLab-OSU/Loom-V4/
architectures=*
includes=Loom_Manager.h
depends=OPEnS RTC
