
#pragma once

#include <Wire.h>

#include "../Loom_Hypnos/Loom_Hypnos.h"
#include "Loom_Manager.h"
#include "Module.h"

#define COUNTER_ADDRESS 0x32 // I2C Counter address

enum COUNTER_TYPE { I2C, MANUAL };

/**
 * Class used to handle keeping track of tips generated by a low-power I2C counter or interrupts
 *
 * @author Will Richards
 */
class Loom_TippingBucket : public Module {
  protected:
    void power_up() override {};
    void power_down() override {};

    void initialize() override;
    void package() override;
    void measure() override;

  public:
    /* Constructor for an I2C based tipping bucket*/
    Loom_TippingBucket(Manager &man, COUNTER_TYPE type, float inchesPerTip = 0.01);

    /* Set an instance of the Hypnos inside the tipping bucket class so we can read RTC data*/
    void setHypnosInstance(Loom_Hypnos &hypnos) { this->hypnosInst = &hypnos; };

    /* Increase the tip count variable by one */
    void incrementCount() { tipCount++; };

    /* Get the rainfall that accumulated over the last hour (calculated based on the Hypnos RTC)*/
    float getHourlyRainfall() { return tipsToInches(hourlyTips); };

    /* Get the total rainfall over the runtime of the device */
    float getTotalRainfall() { return tipsToInches(tipCount); };

  private:
    Manager *manInst = nullptr; // Instance of the manager
    unsigned long tipCount = 0; // The number of tips accumulated by the counter

    /* Hourly Tips Tracker*/
    Loom_Hypnos *hypnosInst = nullptr; // Instance of the hypnos for using RTC
    unsigned long hourlyTips = 0;      // Number of tips recorded in the last hour
    const float inchesPerTip;          // Rainfall represented by one bucket tip
    unsigned long lastTipCount = 0;

    // A fixed minute ring keeps hourly tracking deterministic on the 32 KB SAMD21. The previous
    // pair of deques allocated entries on every measurement and could exhaust RAM in under an
    // hour at the 500 ms interval used by the example.
    static const size_t HISTORY_BUCKET_COUNT = 60;
    static const uint32_t INVALID_MINUTE = UINT32_MAX;
    struct TipHistoryBucket {
        uint32_t minute;
        unsigned long tips;
    };
    TipHistoryBucket tipHistory[HISTORY_BUCKET_COUNT];

    void updateHourlyTips(uint32_t currentTime, unsigned long newTips);
    float tipsToInches(unsigned long tips); // Convert bucket tips to inches of rainfall
};
