# Compiler
CXX = clang++
CXXFLAGS = -std=c++17 -Wall -Wextra -g

# Include search paths (order matters!)
INCLUDES = \
	-I./Testing_Components/Stubs \

# --------------------------
#   Tests
# --------------------------

# Source files to compile
SOURCES = \
    ../src/Loom_Manager.cpp \
    ../src/Radio/Loom_Freewave/Loom_Freewave.cpp \
    ../src/Radio/Loom_Freewave/Tests/Loom_Freewave_Tests.cpp